version: '3'
services:
  tomcat:
    # Tomcat 8.5.41 JDK 1.8
    image: tomcat:alpine
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ../../agents/standard/jsp/agent_classloader.java:/usr/local/tomcat/webapps/ROOT/agent_st.jsp
    networks:
      - apps
  liferay:
    # Liferay Community Edition Portal 7.2.0 CE GA1 (Mueller / Build 7200 / June 4, 2019) JDK 1.8
    image: liferay/portal:7.2.0-ga1
    container_name: liferay
    ports:
      - "8081:8080"
    volumes:
      - ../../agents/standard/jsp/agent_classloader.java:/opt/liferay/tomcat-9.0.17/webapps/ROOT/agent_st.jsp
    networks:
      - apps
networks:
  apps:
    driver: "bridge"
